export const SEARCH_START = 'SEARCH_START';
export const SEARCH_FINISH = 'SEARCH_FINISH';
export const SELECT_SONG_START = 'SELECT_SONG_START';
export const SELECT_SONG_FINISH = 'SELECT_SONG_FINISH';
