export const AUTHENTICATE_START = 'AUTHENTICATE_START';
export const AUTHENTICATE_FINISH = 'AUTHENTICATE_FINISH';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FINISH = 'LOGIN_FINISH';
export const LOGOUT = 'LOGOUT';
